language: csharp
sudo: required
dist: trusty
solution: CAP.sln
dotnet: 2.2.100
mono: none

matrix:
  include:
  - dotnet: 2.2.100
#  - os: linux
#    dist: trusty # Ubuntu 14.04
#    sudo: required
#  - os: osx
#    osx_image: xcode8.3 # macOS 10.12
    
# Run the build script
script:
  - dotnet --info
  - dotnet restore CAP.sln
  - dotnet build CAP.sln
  - dotnet test test/DotNetCore.CAP.Test/DotNetCore.CAP.Test.csproj